-- CreateTable
CREATE TABLE `bonusRule` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `type` ENUM('WEEKLY_TOTAL', 'SINGLE_CUSTOMER') NOT NULL,
    `minAmount` DOUBLE NOT NULL,
    `bonusAmount` DOUBLE NOT NULL,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
